DB_USERNAME: usuario
DB_PASSWORD: clave
DB_HOST: docker_postgresql_protein
DB_PORT: 5432
DB_NAME: BioData

criterio_busqueda: '(structure_3d:true) AND (reviewed:true)'
limit: 10

server: "https://files.wwpdb.org/"
pdb: /opt/data/PDB
file_format: "mmCif"



resolution_threshold: 2.5
max_workers: 15
data_dir: /opt/data/FASTA
output_dir: /opt/data/FASTA/output
merge_name: merge_25

